"""fix price column in subscriptions table

Revision ID: c7f86cdfc1ef
Revises: 1fa8cfa5f934
Create Date: 2025-11-21 20:07:41.041501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f86cdfc1ef'
down_revision: Union[str, Sequence[str], None] = '1fa8cfa5f934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
